apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: framm-web
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kod-digor/framm
    targetRevision: main
    path: k8s/apps/web
  destination:
    server: https://kubernetes.default.svc
    namespace: framm
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
