apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: framm
resources:
  - deployment-web.yaml
  - deployment-worker.yaml
  - service.yaml
  - ingress.yaml
  - hpa.yaml
  - migrate-job.yaml
images:
  # newTag mis à jour automatiquement par la CI (job build-push)
  - name: rg.fr-par.scw.cloud/framm-kod-digor/web
    newTag: 542c01abdbb4138c27c75efb0f176b6b787b7f69
  - name: rg.fr-par.scw.cloud/framm-kod-digor/worker
    newTag: 542c01abdbb4138c27c75efb0f176b6b787b7f69
