apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: framm
resources:
  - deployment-web.yaml
  - deployment-worker.yaml
  - service.yaml
  - ingress.yaml
  - hpa.yaml
  - migrate-job.yaml
images:
  # newTag mis à jour automatiquement par la CI (job build-push)
  - name: rg.fr-par.scw.cloud/framm-kod-digor/web
    newTag: b4e72715654e638c06d00537cf7534204a022b2b
  - name: rg.fr-par.scw.cloud/framm-kod-digor/worker
    newTag: b4e72715654e638c06d00537cf7534204a022b2b
